# -*- coding: utf-8 -*-
"""ASL Detection System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-0gOwcX5UinGir75TZ2KVDV7GWi5B17

# **ASL DETECTION SYSTEM**
"""

import kagglehub
import os
import cv2
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.metrics import Precision, Recall
from tensorflow.keras.callbacks import EarlyStopping

"""# **1. Download Dataset**"""

path = kagglehub.dataset_download(
    "iamavinashkr090502/asl-hand-landmark-and-gesture-dataset"
)

print("Dataset path:", path)

"""# **2. Data Preparation**"""

IMG_SIZE = 96
BATCH_SIZE = 32

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

train_data = datagen.flow_from_directory(
    path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

labels = list(train_data.class_indices.keys())

"""# **3. Transfer Learning Model**"""

base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights='imagenet'
)

for layer in base_model.layers:
    layer.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)

output = Dense(len(labels), activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=[
        'accuracy',
        Precision(name='precision'),
        Recall(name='recall')
    ]
)

"""# **4. Train Model**"""

model.fit(
    train_data,
    validation_data=val_data,
    epochs=10,
    callbacks=[EarlyStopping(patience=3, restore_best_weights=True)]
)

"""# **5. Real-Time Detection**"""

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Error: Webcam not detected")
    exit()

print("Press 'q' to quit")

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame = cv2.flip(frame, 1)

    # ROI box
    h, w, _ = frame.shape
    x1, y1 = int(w*0.3), int(h*0.2)
    x2, y2 = int(w*0.7), int(h*0.8)

    roi = frame[y1:y2, x1:x2]

    # Preprocess
    img = cv2.resize(roi, (IMG_SIZE, IMG_SIZE))
    img = img / 255.0
    img = np.reshape(img, (1, IMG_SIZE, IMG_SIZE, 3))

    # Prediction
    pred = model.predict(img, verbose=0)
    confidence = np.max(pred)
    label = labels[np.argmax(pred)]

    # Display
    if confidence > 0.7:
        text = f"{label} ({confidence:.2f})"
    else:
        text = "Detecting..."

    cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
    cv2.putText(frame, text, (50,50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2)

    cv2.imshow("ASL Detection", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()